/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    testimonials: Testimonial;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'drivers-page': DriversPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'drivers-page': DriversPageSelect<false> | DriversPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path — /blog/<slug>. Auto-filled from the title.
   */
  slug: string;
  /**
   * Unpublish to hide from /blog without deleting.
   */
  published?: boolean | null;
  /**
   * Publication date — drives ordering.
   */
  date: string;
  /**
   * Small eyebrow label above the title.
   */
  kicker?: string | null;
  /**
   * Card summary + meta description.
   */
  excerpt?: string | null;
  byline?: string | null;
  /**
   * Hero image path, e.g. /assets/blog/my-slug.png (1600×900). Place the file in public/assets/blog/.
   */
  hero?: string | null;
  heroAlt?: string | null;
  seoTitle?: string | null;
  /**
   * SEO keywords (press Enter between each).
   */
  keywords?: string[] | null;
  /**
   * Article body in Markdown. Supports ## / ### headings, - and 1. lists, **bold**, *italic*, [label](/link), and > quotes.
   */
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The testimonial itself. Keep it honest and specific.
   */
  quote: string;
  /**
   * Attribution, e.g. a driver name or "Founding Member".
   */
  name: string;
  /**
   * Small line under the name, e.g. "OneHome Driver Program".
   */
  role: string;
  /**
   * Avatar initials. Auto-filled from the name; override if needed.
   */
  initials?: string | null;
  /**
   * Optional pill, e.g. "Founding Member" or "Illustrative".
   */
  badge?: string | null;
  /**
   * Optional headshot. The initials avatar is the fallback when empty.
   */
  photo?: (number | null) | Media;
  /**
   * Unpublish to hide from /drivers without deleting.
   */
  published?: boolean | null;
  /**
   * Manual sort — lower shows first. Defaults to creation order if unset.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility and SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  date?: T;
  kicker?: T;
  excerpt?: T;
  byline?: T;
  hero?: T;
  heroAlt?: T;
  seoTitle?: T;
  keywords?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  initials?: T;
  badge?: T;
  photo?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The count-up ribbon directly under the homepage hero.
   */
  heroStats?:
    | {
        /**
         * e.g. "Spaces · West Memphis".
         */
        label: string;
        /**
         * The number that counts up, e.g. 1800.
         */
        value: number;
        /**
         * Optional, shown before the number, e.g. "$".
         */
        prefix?: string | null;
        /**
         * Optional, shown after the number, e.g. "+" or "K".
         */
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The five lanes on the homepage. Only the card title, blurb, and link live here, not the full per-audience page.
   */
  audienceCards?:
    | {
        title: string;
        /**
         * Short one-line description under the title.
         */
        blurb: string;
        /**
         * Internal path, e.g. /drivers.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Canonical contact details. The one source of truth going forward.
   */
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers-page".
 */
export interface DriversPage {
  id: number;
  /**
   * Full-bleed background video (mp4 URL).
   */
  heroVideoUrl?: string | null;
  eyebrow?: string | null;
  /**
   * The H1.
   */
  heroPunch?: string | null;
  /**
   * The 4-line "Truck doesn't fit in the driveway..." verse.
   */
  verseLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  heroBlurb?: string | null;
  heroNote?: string | null;
  scrollHint?: string | null;
  /**
   * Outriders coin (optional). Falls back to /assets/coin-outriders.png.
   */
  coinImage?: (number | null) | Media;
  storyEyebrow?: string | null;
  /**
   * e.g. "Welcome to the Club".
   */
  storyHeadline?: string | null;
  /**
   * The rendered story paragraphs (first one is the large lead).
   */
  storyParas?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  webinarBody?: string | null;
  /**
   * Vimeo player URL.
   */
  webinarVideoUrl?: string | null;
  founderName?: string | null;
  founderTitle?: string | null;
  /**
   * Two-tone, split on "/": e.g. "Nothing To Lose / Everything To Gain".
   */
  joinHeadline?: string | null;
  /**
   * The 3 free-membership steps.
   */
  membershipSteps?:
    | {
        title: string;
        line: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Two-tone, split on "/": e.g. "Claim Your Free / Driver Membership.".
   */
  joinFreeHeadline?: string | null;
  joinFreeBody?: string | null;
  joinFreeBullets?:
    | {
        bullet: string;
        id?: string | null;
      }[]
    | null;
  coreKicker?: string | null;
  /**
   * Two-tone, split on "/": e.g. "Here's A New & / Better Option.".
   */
  coreHeadline?: string | null;
  coreSubhead?: string | null;
  coreParas?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  coreBlurb?: string | null;
  amenitiesHeadline?: string | null;
  amenitiesIntro?: string | null;
  /**
   * The 8 club amenities carousel slides.
   */
  amenitySlides?:
    | {
        image?: (number | null) | Media;
        name: string;
        spec: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Members call the 25,000 sq ft private drivers club "The Rig Carlton."
   */
  amenitiesFootnote?: string | null;
  valueHeadline?: string | null;
  valueSubhead?: string | null;
  valuePrompt?: string | null;
  valuePrompts?:
    | {
        question: string;
        id?: string | null;
      }[]
    | null;
  valueBlurb?: string | null;
  /**
   * Feeds ComparisonTable — Traditional vs OneHome.
   */
  comparisonRows?:
    | {
        traditional: string;
        oneHome: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Two-tone, split on "/": e.g. "Three Ways To / Get Space.".
   */
  spaceHeadline?: string | null;
  /**
   * The 3 ways to get Space.
   */
  spaceSteps?:
    | {
        title: string;
        line: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  homeHubHeadline?: string | null;
  homeHubBlurb?: string | null;
  /**
   * Home Hub + Fleet Services image tiles.
   */
  everythingTiles?:
    | {
        group: 'Home Hub' | 'Fleet Services';
        label: string;
        line: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * The "Also: Tire Pressure Management ..." line.
   */
  fleetDetail?: string | null;
  /**
   * The "Everything included" categorized menu.
   */
  clubMenu?:
    | {
        category: string;
        items?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  networkHeadline?: string | null;
  networkSubhead?: string | null;
  networkParas?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  networkBlurb?: string | null;
  /**
   * The city names shown as pills.
   */
  planningMarkets?:
    | {
        market: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "1212 MLK Dr".
   */
  hubAddress?: string | null;
  /**
   * e.g. "West Memphis, AR — I-40 / I-55".
   */
  hubAddressSub?: string | null;
  hubBody?: string | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroStats?:
    | T
    | {
        label?: T;
        value?: T;
        prefix?: T;
        suffix?: T;
        id?: T;
      };
  audienceCards?:
    | T
    | {
        title?: T;
        blurb?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers-page_select".
 */
export interface DriversPageSelect<T extends boolean = true> {
  heroVideoUrl?: T;
  eyebrow?: T;
  heroPunch?: T;
  verseLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  heroBlurb?: T;
  heroNote?: T;
  scrollHint?: T;
  coinImage?: T;
  storyEyebrow?: T;
  storyHeadline?: T;
  storyParas?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  webinarBody?: T;
  webinarVideoUrl?: T;
  founderName?: T;
  founderTitle?: T;
  joinHeadline?: T;
  membershipSteps?:
    | T
    | {
        title?: T;
        line?: T;
        image?: T;
        id?: T;
      };
  joinFreeHeadline?: T;
  joinFreeBody?: T;
  joinFreeBullets?:
    | T
    | {
        bullet?: T;
        id?: T;
      };
  coreKicker?: T;
  coreHeadline?: T;
  coreSubhead?: T;
  coreParas?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  coreBlurb?: T;
  amenitiesHeadline?: T;
  amenitiesIntro?: T;
  amenitySlides?:
    | T
    | {
        image?: T;
        name?: T;
        spec?: T;
        id?: T;
      };
  amenitiesFootnote?: T;
  valueHeadline?: T;
  valueSubhead?: T;
  valuePrompt?: T;
  valuePrompts?:
    | T
    | {
        question?: T;
        id?: T;
      };
  valueBlurb?: T;
  comparisonRows?:
    | T
    | {
        traditional?: T;
        oneHome?: T;
        id?: T;
      };
  spaceHeadline?: T;
  spaceSteps?:
    | T
    | {
        title?: T;
        line?: T;
        image?: T;
        id?: T;
      };
  homeHubHeadline?: T;
  homeHubBlurb?: T;
  everythingTiles?:
    | T
    | {
        group?: T;
        label?: T;
        line?: T;
        image?: T;
        id?: T;
      };
  fleetDetail?: T;
  clubMenu?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  networkHeadline?: T;
  networkSubhead?: T;
  networkParas?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  networkBlurb?: T;
  planningMarkets?:
    | T
    | {
        market?: T;
        id?: T;
      };
  hubAddress?: T;
  hubAddressSub?: T;
  hubBody?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}